############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1
identifier = "accueil"

[[main]]
name = "Vie locale"
url = "/local/"
weight = 2
identifier = "local"

[[main]]
parent = "local"
name = "Associations"
url = "/local/associations/"
weight = 1

[[main]]
parent = "local"
name = "Bon voisinage"
url = "/local/bon-voisinage/"
weight = 2

[[main]]
parent = "local"
name = "Démarches administratives"
url = "/local/demarches-administratives/"
weight = 3

[[main]]
parent = "local"
name = "École"
url = "/local/ecole/"
weight = 4

[[main]]
parent = "local"
name = "Entreprises"
url = "/local/entreprises/"
weight = 5

[[main]]
parent = "local"
name = "Gestion des déchets"
url = "/local/gestion-des-dechets/"
weight = 6

[[main]]
parent = "local"
name = "Location salle des fêtes/stade"
url = "/local/salle-des-fetes-stade/"
weight = 7

[[main]]
parent = "local"
name = "Patrimoine"
url = "/local/patrimoine/"
weight = 8

[[main]]
name = "Tourisme"
url = "/tourisme/"
weight = 3
identifier = "tourisme"

[[main]]
parent = "tourisme"
name = "Hébergement"
url = "/tourisme/hebergement/"
weight = 1

[[main]]
parent = "tourisme"
name = "Loisirs"
url = "/tourisme/loisirs/"
weight = 2

[[main]]
parent = "tourisme"
name = "Marchés"
url = "/tourisme/marches/"
weight = 3

[[main]]
parent = "tourisme"
name = "Restauration"
url = "/tourisme/restauration/"
weight = 4

[[main]]
name = "Conseil municipal"
url = "/conseil-municipal/"
weight = 4
identifier = "conseil-municipal"

[[main]]
parent = "conseil-municipal"
name = "Les élus"
url = "/conseil-municipal/les-elus/"
weight = 1

[[main]]
parent = "conseil-municipal"
name = "Arrêtés, délibérations et procès-verbaux"
url = "/conseil-municipal/compte-rendus/"
weight = 2

# footer menu
[[footer]]
name = "Mentions légales"
url = "/legal"
weight = 1
